version: "3.8"

networks:
  corp:
    driver: bridge

services:
  server:
    platform: linux/amd64
    container_name: server
    build:
      dockerfile: ./apps/server/Dockerfile
      args:
        NODE_ENV: "production"
        BUILD_FLAG: ""
    image: events-api
    ports:
      - 80:80
    environment:
      NODE_ENV: "production"
      PORT: 80
    networks:
      - corp
    restart: on-failure