name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-with-docker-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: 'AWS login'
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
      - run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g5v1k6e9
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: 'Install Dependencies'
        run: npm install
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build images'
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npx nx build server 
#         run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npx nx container server
      - name: 'COPY'
        run: docker tag events/server:latest public.ecr.aws/g5v1k6e9/events-api:latest
      - name: 'Deploy'
        run: docker push public.ecr.aws/g5v1k6e9/events-api:latest
     
